baseURL = 'https://networkpx.com/'
languageCode = 'en-us'
title = 'My Website'
theme = "paper"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10